config/routes.rb
Rails.application.routes.draw do
  resources :courses, only: [:index, :show]

  get 'user/register', to: 'users#new'
  post 'user/register', to: 'users#create'
  get 'instructor/register', to: 'instructors#new'
  post 'instructor/register', to: 'instructors#create'
  get 'user/verify', to: 'users#verify'
  post 'user/verify', to: 'users#postVerify'  
  get 'instructor/verify', to: 'instructors#verify'
  post 'instructor/verify', to: 'instructors#postVerify'  
  post 'sms', to: 'users#sms'
  post 'send_otp', to: 'users#send_otp'
  get '/auth/auth0', to: 'users#google_oauth2'
  get '/auth/auth0/callback', to: 'users#google_oauth2'
  get '/user/login', to: 'users#login_form' 
  post '/user/login', to: 'users#login'
  get '/user/signup', to: 'users#signup'
  post '/user/signup', to: 'users#verified'
  get '/instructor/login', to: 'instructors#login_form' 
  post '/instructor/login', to: 'instructors#login'
  get '/instructor/signup', to: 'instructors#signup'
  post '/instructor/signup', to: 'instructors#verified'
  post '/logout', to: 'instructor#logout'
  get '/course/new', to: 'courses#new'
  post '/course/create', to: 'courses#create'
  get '/content/new', to: 'courses_contents#new'
  post '/content/create', to: 'courses_contents#create'
  get '/course/show/:id', to: 'courses#show'
  get '/course/index', to: 'courses#index'
  post '/course/payment', to: 'payments#create'

end

app/models/instructor.rb
class Instructor < ApplicationRecord
    has_many :courses
    has_secure_password

    validates :full_name, presence: true
    validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/ }
    validates :mobile_number, presence: true
end

app/controllers/instructors_controller.rb
require 'bulk_sms_service' 
require 'twilio-ruby'
require_relative "../../lib/json_web_token"


class InstructorsController < ApplicationController
  skip_before_action :verify_authenticity_token, only:[:sms, :send_otp]
  def new
    @instructor = Instructor.new
  end

  def create
    @instructor = User.new(instructor_params)
    @email = @instructor.email
    session[:instructor] = @instructor
    mailOTP = SecureRandom.random_number(1_000_000).to_s.rjust(6, '0')
    smsOTP = SecureRandom.random_number(1_000_000).to_s.rjust(6, '0')
    account_sid = ENV['TWILIO_ACCOUNT_SID']
    auth_token = ENV['TWILIO_AUTH_TOKEN']
    @client = Twilio::REST::Client.new(account_sid, auth_token)

    message = @client.messages
   .create(
        from: '+15673611296',
        body: "your 2-step Verification OTP is #{smsOTP}",
        to: '+917310156773'
      )
    session[:registration_mailOTP] = mailOTP
    session[:registration_smsOTP] = smsOTP
    UserMailer.registration_otp(@email,mailOTP).deliver_now
    redirect_to instructor_verify_path
  end

  def postVerify
    def verify

    end
    entered_smsOTP = params[:smsOTP]
    entered_mailOTP = params[:mailOTP]
    stored_smsOTP = session[:registration_smsOTP]
    stored_mailOTP = session[:registration_mailOTP]
  instructor = Instructor.new(session[:instructor])
  if entered_smsOTP == stored_smsOTP && entered_mailOTP == stored_mailOTP
      if instructor.save
      instructor.save
      session.delete(:registration_smsOTP) 
      session.delete(:registration_mailOTP) 
      session.delete(:instructor)
      redirect_to instructor_login_path
      # render json: {message: "user saved in database"}
      # redirect_to root_path, notice: "OTP verified successfully!"
      else
        render json: { errors: instructor.errors.full_messages, status: :unprocessable_entity }
      end
    else
    #   flash.now[:alert] = "Invalid OTP. Please try again."
      render :verify
    render json: {error: "OTP is invalid"}

    end
  end

  def login
    def login_form
    end
    email = params[:email]
    password = params[:password]
    @instructor = Instructor.find_by(email: email)
    if @instructor && @instructor.authenticate(password)
    session[:id] = @instructor.id
    mailOTP = SecureRandom.random_number(1_000_000).to_s.rjust(6, '0')
    session[:login_mailOTP] = mailOTP
    UserMailer.registration_otp(email,mailOTP).deliver_now
    redirect_to instructor_signup_path
      
    else
      render json: {error: "instructor does not exist"}
    end
  end

  def verified
    if session[:login_mailOTP] == params[:mailOTP]
      id = session[:id]
      payload={ instructor_id: id}
      token = ::JsonWebToken.encode(payload) 
      session[:token] = token 
      session.delete(:login_mailOTP)
      session.delete(:id)
      redirect_to course_new_path
    else
      flash.now[:alert] = "Invalid OTP. Please try again."
    render json: {error: "OTP is invalid"}
    end
  end

  def logout
    session.delete(:token)
    redirect_to instructor_login_path
  end


  def instructor_params
    params.require(:instructor).permit(:full_name, :email, :mobile_number, :password, :password_confirmation)
  end
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/views/instructors/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/instructors/login_form.html.erb
<div class="col-lg-12">
  <div class="card mt-5 mb-5">
    <div class="card-body">
      <h2 class="text-center">Login </h2>
    </div>
  </div>
</div>

<%= form_tag instructor_login_path, method: :post do %>
<%= content_tag :div, class: 'my-div', style: 'border: solid black 2px;width:50%;height:300px;margin-left: 25%;background-color:#d0caed  ' do %>
<div class="form-row" style="margin-left: 26%; margin-top:8%">
    <%= label_tag :email%>
    <%= text_field_tag :email %>
  </div>
  <div class="form-row" style="margin-left: 27%; margin-top:8%">
    <%= label_tag :password %>
    <%= password_field_tag :password %>
  </div>
  <div class="form-row" style="text-align:center; margin-top:12%">
    <%= submit_tag "Login" %>
  <% end %>
  <% end %>

app/views/instructors/new.html.erb
<div class="col-lg-12">
    <div class="card mt-5 mb-5">
      <div class="card-body">
        <h2 class="text-center">Register New instructor</h2>
      </div>
    </div>
  </div>
    <%= form_for @instructor, url: instructor_register_path, method: :post do |f| %>
    <%= content_tag :div, class: 'my-div', style: 'border: solid black 2px;width:50%;height:300px;margin-left: 25%;background-color:#d0caed  ' do %>
    <div class="form-row">
            <%= f.label :full_name,  style:'margin-left: 23%; margin-top:2%' %>
              <%= f.text_field :full_name,  style:'margin-left: 14%'  %>
            </div>
            <div class="form-row">
                <%= f.label :mobile_number,  style:'margin-left: 23%; margin-top:2%'  %>
                <%= f.text_field :mobile_number ,  style:'margin-left: 14%' %>
            </div>
            <div class="form-row">
            <%= f.label :email,  style:'margin-left: 23%; margin-top:2%'  %>
              <%= f.email_field :email,  style:'margin-left: 19%'  %>
            </div>
            <div class="form-row">
            <%= f.label :password,  style:'margin-left: 23%; margin-top:2%'  %>
              <%= f.password_field :password,  style:'margin-left: 15%'  %>
            </div>
            <div class="form-row">
            <%= f.label :password_confirmation,  style:'margin-left: 23%; margin-top:2%'  %>
              <%= f.password_field :password_confirmation,  style:'margin-left: 0.5%'  %>
            </div>
            <div class="form-row">
            <%= f.submit "Register",  style:'margin-left: 23%; margin-top:3%; background-color:black; color:white'  %>
          </div>
      <% end %>
      <% end %>
  

app/views/instructors/signup.html.erb
<h1>OTP Verification</h1>
<% if flash.now[:alert] %>
  <div class="alert alert-danger">
    <%= flash.now[:alert] %>
  </div>
<% end %>

<%= form_tag instructor_signup_path, method: :post do %>
  <div class="form-group">
    <%= label_tag :mailOTP, "Enter MAIL-OTP:" %>
    <%= text_field_tag :mailOTP, nil, class: "form-control" %>
  </div>
  <%= submit_tag "Verify OTP", class: "btn btn-primary" %>
<% end %>

app/views/instructors/verify.html.erb
<h1>OTP Verification</h1>
<% if flash.now[:alert] %>
  <div class="alert alert-danger">
    <%= flash.now[:alert] %>
  </div>
<% end %>

<%= form_tag instructor_verify_path, method: :post do %>
  <div class="form-group">
    <%= label_tag :smsOTP, "Enter SMS-OTP:" %>
    <%= text_field_tag :smsOTP, nil, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= label_tag :mailOTP, "Enter MAIL-OTP:" %>
    <%= text_field_tag :mailOTP, nil, class: "form-control" %>
  </div>
  <%= submit_tag "Verify OTP", class: "btn btn-primary" %>
<% end %>