config/routes.rb
Rails.application.routes.draw do
  resources :courses, only: [:index, :show]

  get 'user/register', to: 'users#new'
  post 'user/register', to: 'users#create'
  get 'instructor/register', to: 'instructors#new'
  post 'instructor/register', to: 'instructors#create'
  get 'user/verify', to: 'users#verify'
  post 'user/verify', to: 'users#postVerify'  
  get 'instructor/verify', to: 'instructors#verify'
  post 'instructor/verify', to: 'instructors#postVerify'  
  post 'sms', to: 'users#sms'
  post 'send_otp', to: 'users#send_otp'
  get '/auth/auth0', to: 'users#google_oauth2'
  get '/auth/auth0/callback', to: 'users#google_oauth2'
  get '/user/login', to: 'users#login_form' 
  post '/user/login', to: 'users#login'
  get '/user/signup', to: 'users#signup'
  post '/user/signup', to: 'users#verified'
  get '/instructor/login', to: 'instructors#login_form' 
  post '/instructor/login', to: 'instructors#login'
  get '/instructor/signup', to: 'instructors#signup'
  post '/instructor/signup', to: 'instructors#verified'
  post '/logout', to: 'instructor#logout'
  get '/course/new', to: 'courses#new'
  post '/course/create', to: 'courses#create'
  get '/content/new', to: 'courses_contents#new'
  post '/content/create', to: 'courses_contents#create'
  get '/course/show/:id', to: 'courses#show'
  get '/course/index', to: 'courses#index'
  post '/course/payment', to: 'payments#create'

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
    before_action :authenticate_instructor, only: [:new, :create]
    def new
      @course = Course.new
    end
  
    def create
        @course = @current_instructor.courses.build(course_params)
      if @course.save
        name = @course.name
        session[:name] = Course.find_by(name:name).id
        
        redirect_to content_new_path
      else
        render 'new'
      end
    end
  
    def index
      @course = Course.all
    end

    def show
      @course = Course.find(params[:id])
      
    end

    private
  
    def course_params
      params.require(:course).permit(:name, :description, :price)
    end

    def authenticate_instructor
      token = session[:token]
      verify = ::JsonWebToken.decode(token)
      id = verify['instructor_id']
      @current_instructor = Instructor.find_by(id: id)
    end
end
  

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/index.html.erb
<%=render 'shared/navbar' %>
<h1>Uploaded Videos</h1>
<ul>
  <% @course.each do |course| %>
  <% content_urls = course.course_contents.pluck(:content_url) %>
  <% content_types = course.course_contents.pluck(:content_type) %>
  <% content_urls.each do |content_url| %>
  <% content_types.each do |content_type| %>
    <li>
      <h2><%= course.name %> </h2>
      <p><%= course.description %></p>
      <h3><%= course.price %></h3>
      <p>
        <%= link_to 'Download Document', content_type %>
      </p>
     <a href="http://localhost:3000/course/show/<%= course.id %>">watch Video</a>
     <%= link_to "download Video", content_url %>
     <%= form_tag course_payment_path, method: 'post' do %>
     <script
       src="https://checkout.stripe.com/checkout.js" class="stripe-button"
       data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
       data-description="<%= course.name %>"
       data-amount="<%= course.price * 100 %>"
       data-locale="auto"
       data-currency="inr">
     </script>
   <% end %>
   
   <%= link_to 'Back to Courses', courses_path %>
</li>
<% end %>
<% end %>
<% end %>
</ul>

app/views/courses/new.html.erb
<%= form_for @course, url: course_create_path, method: :post do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>

  <%= f.submit 'Create Course' %>
<% end %>

app/views/courses/show.html.erb
<h1>Video Details</h1>
<% content_urls = @course.course_contents.pluck(:content_url) %>
<% content_urls.each do |content_url| %>
<video width="640" height="360" controls>
  <source src="<%= content_url %>" type="video/mp4">
  Your browser does not support the video tag.
</video>
<% end %>